/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author abdelwahed
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    panels.adduser_panel p1;
    panels.addgroup_panel p2;
    panels.changeinfo_panel p3;
    panels.usertogroup_panel p4;
    GridBagLayout layout = new GridBagLayout();
    
    public main() {
        initComponents();
        
        p1 = new panels.adduser_panel();
        p2 = new panels.addgroup_panel();
        p3 = new panels.changeinfo_panel();
        p4 = new panels.usertogroup_panel();
        
        dynamicpanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        
        dynamicpanel.add(p1 ,c);
        dynamicpanel.add(p2 ,c);
        dynamicpanel.add(p3 ,c);
        dynamicpanel.add(p4 ,c);
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dynamicpanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        adduser_jButton = new javax.swing.JButton();
        addgroup_jButton = new javax.swing.JButton();
        usertogroup_jButton = new javax.swing.JButton();
        change_jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dynamicpanel.setPreferredSize(new java.awt.Dimension(388, 400));

        javax.swing.GroupLayout dynamicpanelLayout = new javax.swing.GroupLayout(dynamicpanel);
        dynamicpanel.setLayout(dynamicpanelLayout);
        dynamicpanelLayout.setHorizontalGroup(
            dynamicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );
        dynamicpanelLayout.setVerticalGroup(
            dynamicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        getContentPane().add(dynamicpanel, java.awt.BorderLayout.CENTER);

        adduser_jButton.setBackground(java.awt.Color.blue);
        adduser_jButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        adduser_jButton.setForeground(java.awt.Color.white);
        adduser_jButton.setText("Create/delete Users");
        adduser_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduser_jButtonActionPerformed(evt);
            }
        });

        addgroup_jButton.setBackground(java.awt.Color.blue);
        addgroup_jButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        addgroup_jButton.setForeground(java.awt.Color.white);
        addgroup_jButton.setText("Create/Delete Groups");
        addgroup_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addgroup_jButtonActionPerformed(evt);
            }
        });

        usertogroup_jButton.setBackground(java.awt.Color.blue);
        usertogroup_jButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        usertogroup_jButton.setForeground(java.awt.Color.white);
        usertogroup_jButton.setText("Add Users To Groups");
        usertogroup_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertogroup_jButtonActionPerformed(evt);
            }
        });

        change_jButton4.setBackground(java.awt.Color.blue);
        change_jButton4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        change_jButton4.setForeground(java.awt.Color.white);
        change_jButton4.setText("Change Users Info");
        change_jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addgroup_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adduser_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(change_jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usertogroup_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(adduser_jButton)
                .addGap(34, 34, 34)
                .addComponent(addgroup_jButton)
                .addGap(34, 34, 34)
                .addComponent(change_jButton4)
                .addGap(34, 34, 34)
                .addComponent(usertogroup_jButton)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addgroup_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addgroup_jButtonActionPerformed
        // TODO add your handling code here:
        p2.setVisible(true);
        p1.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_addgroup_jButtonActionPerformed

    private void adduser_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduser_jButtonActionPerformed
        // TODO add your handling code here:
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_adduser_jButtonActionPerformed

    private void change_jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_jButton4ActionPerformed
        // TODO add your handling code here:
        p3.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
        p4.setVisible(false);
    }//GEN-LAST:event_change_jButton4ActionPerformed

    private void usertogroup_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertogroup_jButtonActionPerformed
        // TODO add your handling code here:
        p4.setVisible(true);
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
    }//GEN-LAST:event_usertogroup_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addgroup_jButton;
    private javax.swing.JButton adduser_jButton;
    private javax.swing.JButton change_jButton4;
    private javax.swing.JPanel dynamicpanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton usertogroup_jButton;
    // End of variables declaration//GEN-END:variables
}
