/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.Color;

/**
 *
 * @author abdelwahed
 */
public class adduser_panel extends javax.swing.JPanel {

    /**
     * Creates new form adduser_panel
     */
    public adduser_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namep1_jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        addp1_jButton = new javax.swing.JButton();
        delp1_jButton = new javax.swing.JButton();
        msgp1_jLabel3 = new javax.swing.JLabel();

        namep1_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namep1_jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel1.setText("Enter User Name ..!");

        addp1_jButton.setBackground(java.awt.Color.green);
        addp1_jButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        addp1_jButton.setForeground(java.awt.Color.black);
        addp1_jButton.setText("Create");
        addp1_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addp1_jButtonActionPerformed(evt);
            }
        });

        delp1_jButton.setBackground(java.awt.Color.green);
        delp1_jButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        delp1_jButton.setForeground(java.awt.Color.black);
        delp1_jButton.setText("Delete");
        delp1_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delp1_jButtonActionPerformed(evt);
            }
        });

        msgp1_jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namep1_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addp1_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delp1_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(msgp1_jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namep1_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addp1_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delp1_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgp1_jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void namep1_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namep1_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namep1_jTextField1ActionPerformed

    private void addp1_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addp1_jButtonActionPerformed
        // TODO add your handling code here:
        project1.docommand p = new project1.docommand();
        
        if(namep1_jTextField1.getText().isEmpty())
        {
            msgp1_jLabel3.setForeground(Color.red);
            msgp1_jLabel3.setText("Apove white box is empty ..!");
        }
        else
        {
            String command1 = "useradd -m -s /bin/bash ";
            String command2 = namep1_jTextField1.getText();
            String total_command3 = command1 + command2;
           if(p.command(total_command3))
           {
               msgp1_jLabel3.setForeground(Color.black);
               msgp1_jLabel3.setText(command2+" was created");
           }
           
        }
    }//GEN-LAST:event_addp1_jButtonActionPerformed

    private void delp1_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delp1_jButtonActionPerformed
        // TODO add your handling code here:
        
        project1.docommand p = new project1.docommand();
        
        if(namep1_jTextField1.getText().isEmpty())
        {
            msgp1_jLabel3.setForeground(Color.red);
            msgp1_jLabel3.setText("Apove white box is empty ..!");
        }
        else
        {
            String command11 = "userdel -r ";
            String command22 = namep1_jTextField1.getText();
            String total_command33 = command11 + command22 ;
           if(p.command(total_command33))
           {
               msgp1_jLabel3.setForeground(Color.black);
               msgp1_jLabel3.setText(command22+" was deleted");
           }
           
        }
    }//GEN-LAST:event_delp1_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addp1_jButton;
    private javax.swing.JButton delp1_jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel msgp1_jLabel3;
    private javax.swing.JTextField namep1_jTextField1;
    // End of variables declaration//GEN-END:variables
}
