/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.Color;

/**
 *
 * @author abdelwahed
 */
public class changeinfo_panel extends javax.swing.JPanel {

    /**
     * Creates new form changeinfo_panel
     */
    public changeinfo_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        user1_jTextField = new javax.swing.JTextField();
        user11_jTextField = new javax.swing.JTextField();
        directory1_jTextField = new javax.swing.JTextField();
        directory11_jTextField = new javax.swing.JTextField();
        id1_jTextField = new javax.swing.JTextField();
        id11_jTextField = new javax.swing.JTextField();
        confirm1_jButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        msg1_jLabel = new javax.swing.JLabel();
        msg2_jLabel = new javax.swing.JLabel();
        confirm2_jButton = new javax.swing.JButton();
        confirm3_jButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(311, 250));

        user11_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user11_jTextFieldActionPerformed(evt);
            }
        });

        confirm1_jButton.setBackground(java.awt.Color.green);
        confirm1_jButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirm1_jButton.setForeground(java.awt.Color.white);
        confirm1_jButton.setText("Confirm");
        confirm1_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm1_jButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("user Name");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Directory");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Primary ID");

        jLabel7.setText("User");

        jLabel8.setText("New Name");

        jLabel9.setText("User");

        jLabel10.setText("Directory");

        jLabel11.setText("User");

        jLabel12.setText("New ID");

        msg1_jLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        msg1_jLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        msg2_jLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        msg2_jLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        confirm2_jButton.setBackground(java.awt.Color.green);
        confirm2_jButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirm2_jButton.setForeground(java.awt.Color.white);
        confirm2_jButton.setText("Confirm");
        confirm2_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm2_jButtonActionPerformed(evt);
            }
        });

        confirm3_jButton.setBackground(java.awt.Color.green);
        confirm3_jButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        confirm3_jButton.setForeground(java.awt.Color.white);
        confirm3_jButton.setText("Confirm");
        confirm3_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm3_jButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(user1_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(user11_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(confirm1_jButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel10)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(id1_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(id11_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(confirm3_jButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(directory1_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(directory11_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirm2_jButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(msg2_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(msg1_jLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user1_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user11_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm1_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directory1_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(directory11_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(confirm2_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id1_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id11_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(confirm3_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(msg1_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(msg2_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirm1_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm1_jButtonActionPerformed
        // TODO add your handling code here:
        project1.docommand p = new project1.docommand();
        if(user1_jTextField.getText().isEmpty() || user11_jTextField.getText().isEmpty())
        {
            msg1_jLabel.setForeground(Color.red);
            msg2_jLabel.setForeground(Color.red);
            msg1_jLabel.setText("Sorry, User or");
            msg2_jLabel.setText("new name is empty ..!");
        }
        
        else
        {
        String command1 = "usermod -l "; 
        String command2 = user11_jTextField.getText() +" "+user1_jTextField.getText();
        String total_command = command1 + command2 ;//usermod -l hhh ismail
        
        if(p.command(total_command))
        {
            msg1_jLabel.setForeground(Color.black);
            msg2_jLabel.setForeground(Color.black);
            msg1_jLabel.setText(user1_jTextField.getText()+" was updated");
            msg2_jLabel.setText("  successfully "+"to "+user11_jTextField.getText());
        }
        }
        
    }//GEN-LAST:event_confirm1_jButtonActionPerformed

    private void user11_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user11_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user11_jTextFieldActionPerformed

    private void confirm2_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm2_jButtonActionPerformed
        // TODO add your handling code here:
        project1.docommand p = new project1.docommand();
        if(directory1_jTextField.getText().isEmpty() || directory11_jTextField.getText().isEmpty())
        {
            msg1_jLabel.setForeground(Color.red);
            msg2_jLabel.setForeground(Color.red);
            msg1_jLabel.setText("Sorry, User or new");
            msg2_jLabel.setText("directory is empty ..!");
        }
        
        else
        {
        String command1 = "usermod -d /home/"; 
        String command2 = directory11_jTextField.getText() +" -m "+directory1_jTextField.getText();
        String total_command = command1 + command2 ;
        
        if(p.command(total_command))
        {
            msg1_jLabel.setForeground(Color.black);
            msg2_jLabel.setForeground(Color.black);
            msg1_jLabel.setText(directory1_jTextField.getText()+"'s "+"Directory was");
            msg2_jLabel.setText("updated successfully");
        }
        }
    }//GEN-LAST:event_confirm2_jButtonActionPerformed

    private void confirm3_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm3_jButtonActionPerformed
        // TODO add your handling code here:
        project1.docommand p = new project1.docommand();
        if(id1_jTextField.getText().isEmpty() || id11_jTextField.getText().isEmpty())
        {
            msg1_jLabel.setForeground(Color.red);
            msg2_jLabel.setForeground(Color.red);
            msg1_jLabel.setText("Sorry, User or new");
            msg2_jLabel.setText("new ID is empty ..!");
        }
        
        else
        {
        String command1 = "usermod -u "; 
        String command2 = id11_jTextField.getText() +" "+id1_jTextField.getText();
        String total_command = command1 + command2 ;
        
        if(p.command(total_command))
        {
            msg1_jLabel.setForeground(Color.black);
            msg2_jLabel.setForeground(Color.black);
            msg1_jLabel.setText(id1_jTextField.getText()+"'s "+"ID was");
            msg2_jLabel.setText("updated successfully");
        }
        }
    }//GEN-LAST:event_confirm3_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm1_jButton;
    private javax.swing.JButton confirm2_jButton;
    private javax.swing.JButton confirm3_jButton;
    private javax.swing.JTextField directory11_jTextField;
    private javax.swing.JTextField directory1_jTextField;
    private javax.swing.JTextField id11_jTextField;
    private javax.swing.JTextField id1_jTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msg1_jLabel;
    private javax.swing.JLabel msg2_jLabel;
    private javax.swing.JTextField user11_jTextField;
    private javax.swing.JTextField user1_jTextField;
    // End of variables declaration//GEN-END:variables
}
