/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.Color;

/**
 *
 * @author abdelwahed
 */
public class usertogroup_panel extends javax.swing.JPanel {

    /**
     * Creates new form usertogroup_panel
     */
    public usertogroup_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_jButton = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();
        user_jTextField = new javax.swing.JTextField();
        group_jTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        msg1_jLabel = new javax.swing.JLabel();
        msg2_jLabel = new javax.swing.JLabel();

        add_jButton.setBackground(java.awt.Color.green);
        add_jButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        add_jButton.setForeground(java.awt.Color.black);
        add_jButton.setText("Add");
        add_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_jButtonActionPerformed(evt);
            }
        });

        jComboBox.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NewUser", "OldUser" }));

        group_jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group_jTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel1.setText("User Name");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel2.setText("Group Name");

        msg1_jLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        msg1_jLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        msg2_jLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        msg2_jLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(group_jTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(msg1_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(msg2_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(group_jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msg1_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(msg2_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void group_jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_group_jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_group_jTextFieldActionPerformed

    private void add_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_jButtonActionPerformed
        // TODO add your handling code here:
        project1.docommand n = new project1.docommand();
        
        if(user_jTextField.getText().isEmpty() || group_jTextField.getText().isEmpty())
        {
            msg1_jLabel.setForeground(Color.red);
            msg2_jLabel.setForeground(Color.red);
            msg1_jLabel.setText("User or group name");
            msg2_jLabel.setText("is empty ..!");
        }
        else
        {
            if(jComboBox.getSelectedItem().equals("NewUser"))
            {
            String commandn1 = "useradd -m -s /bin/bash -G ";
            String commandn2 = group_jTextField.getText();
            String commandn3 = user_jTextField.getText();
            String total_commandn = commandn1 + commandn2 +" "+ commandn3;
            if(n.command(total_commandn))
            {
            msg1_jLabel.setForeground(Color.black);
            msg2_jLabel.setForeground(Color.black);
            msg1_jLabel.setText(commandn3+" was added to");
            msg2_jLabel.setText(commandn2+" successfully");
            }
            }
            
            else
            {
            String commandc1 = "usermod -G ";
            String commandc2 = group_jTextField.getText();
            String commandc3 = user_jTextField.getText();
            String total_commandc = commandc1 + commandc2 +" "+ commandc3;
            if(n.command(total_commandc))
            {
            msg1_jLabel.setForeground(Color.black);
            msg2_jLabel.setForeground(Color.black);
            msg1_jLabel.setText(commandc3+" was added to");
            msg2_jLabel.setText(commandc2+" successfully");
            }
            }
           
        }
    }//GEN-LAST:event_add_jButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_jButton;
    private javax.swing.JTextField group_jTextField;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel msg1_jLabel;
    private javax.swing.JLabel msg2_jLabel;
    private javax.swing.JTextField user_jTextField;
    // End of variables declaration//GEN-END:variables
}
